@extends('admin.app')
@section('content')
<div class="content media-admin"><div class="admin-page-heading"><div><p class="admin-eyebrow">Website content</p><h1>Community Outreach</h1><p>Manage the outreach programmes visitors see on the Programmes page.</p></div><button class="admin-add-button" type="button" onclick="document.getElementById('add-outreach-programme').showModal()"><i class="fas fa-plus"></i> Add programme</button></div>
@if(session('success')) <div class="admin-alert success"><i class="fas fa-check-circle"></i>{{ session('success') }}</div> @endif
@if($errors->any()) <div class="admin-alert error"><i class="fas fa-circle-exclamation"></i>{{ $errors->first() }}</div> @endif
<div class="outreach-admin-list">@forelse($programmes as $programme)<article class="outreach-admin-item {{ $programme->status === 'inactive' ? 'is-hidden' : '' }}"><div class="outreach-admin-icon colour-{{ $programme->colour }}"><i class="fas {{ $programme->icon }}"></i></div><div class="outreach-admin-copy"><div class="flex items-center gap-3"><h2>{{ $programme->title }}</h2><span class="admin-status {{ $programme->status }}">{{ $programme->status === 'active' ? 'Live' : 'Hidden' }}</span></div><p>{{ $programme->description }}</p><small>Position {{ $programme->display_order }} · {{ ucfirst($programme->colour) }} accent</small></div><div class="outreach-admin-actions"><button class="admin-quiet-button" type="button" onclick="document.getElementById('edit-outreach-{{ $programme->id }}').showModal()"><i class="fas fa-pen"></i> Edit</button><form method="POST" action="{{ route('outreach.delete', $programme) }}" onsubmit="return confirm('Remove this outreach programme?')">@csrf @method('DELETE')<button class="admin-delete-button" title="Remove programme"><i class="fas fa-trash"></i></button></form></div></article><dialog id="edit-outreach-{{ $programme->id }}" class="admin-dialog"><div class="admin-dialog-title"><div><p class="admin-eyebrow">Outreach programme</p><h2>Edit programme</h2></div><button type="button" onclick="this.closest('dialog').close()"><i class="fas fa-xmark"></i></button></div><form method="POST" action="{{ route('outreach.update', $programme) }}" class="admin-form">@csrf @method('PUT') @include('admin.partials.outreach-form', ['button' => 'Save changes', 'cancel' => true])</form></dialog>@empty <div class="admin-empty-state"><i class="fas fa-hands-helping"></i><h2>No outreach programmes yet</h2><p>Add an item to display it on the Programmes page.</p></div>@endforelse</div></div>
<dialog id="add-outreach-programme" class="admin-dialog"><div class="admin-dialog-title"><div><p class="admin-eyebrow">New outreach programme</p><h2>Add programme</h2></div><button type="button" onclick="this.closest('dialog').close()"><i class="fas fa-xmark"></i></button></div><form method="POST" action="{{ route('outreach.store') }}" class="admin-form">@csrf @include('admin.partials.outreach-form', ['programme' => null, 'button' => 'Add programme', 'cancel' => true])</form></dialog>
@include('admin.partials.content-admin-styles')
@endsection
